hash-format = "sha256"

[[files]]
file = "mods/accessories.pw.toml"
hash = "98cf4869a7679e976f608e4eee0144a3e0d383fbdea1b40f1f58ec8435f21e47"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "75dc768530ee3b928b85766dface34806e0c3fd62d2970e60ce1083f04d753bb"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2492a7266fab4c2ff411612180974b98510afb66a18e640f4de63ad615dd1e9e"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "5c53336a2e46a334336a2a40e3fe18af4656a76e66b83b306362962136c92d8c"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "2ea3d87ffc2806e4bcb6ee9f5a35bdb4588b29030aba235dc7616d1833349d5b"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "0c6982d793283b27ef35fdc3b57b7b9554fbc162c03ac7431ebbee9b1d5b241c"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "4b8ffbe47270effb2da83ff2fba6e5dea0158a515033b61a484a21aae6146a76"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
hash = "f04f6619202e8b2b22e33c4ce152f879633577d82ada897327603c050da601df"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "22f9614b5e06136fa385694a428e4aa71319893a095c3d7cddf1420a7f1186b4"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "d1c4b6ef4ff3b07a857c13462bce0e824aa167d69739025ef2bd8822497e76ca"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "94a719c6336dce30b5092d4241a49e6739b03959bd59da9babf5b2d22b028890"
metafile = true

[[files]]
file = "mods/create-structures-arise.pw.toml"
hash = "2a97d09cfad3bdc1cd0f6faa65bc7577effda9ef8c17d631c101266e1edceff0"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "754b65581daa4a2d8462d5e62b43555a85a2f24106e8662925a1adefcc9f07cf"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "a1b7ea87dc91f24519a4a4cf8170479c3007fb1c651d04d0ea9515a42f42539c"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "ec2f847977196cfdbde04c23cb9d0389ef86b7b2276397b4bcf5e0b068280c96"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "645057017936ddc2d2712164654ad63726da0d94632ea4fc09d990bddab95da0"
metafile = true

[[files]]
file = "mods/enders-delight.pw.toml"
hash = "475bd3dc8729184dab6a090f6645b1c30bdc1043386fd25968de64aa969f0b47"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "adcd67c419f4c88858298958287b1658e9a81b7d50c6794769ca01c8b856d3a6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c784cee4a8eed3f2b36172b8c5a119a62a28880d15e7f169947c935bf3bf4bb3"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "91d77e070777044a75b782afc2e2267890e929069e264c3d0e9201eff7c207c1"
metafile = true

[[files]]
file = "mods/farmers-structures.pw.toml"
hash = "837a4cd76074b9bcec0eca2e4f7dda9e76f058e154e9a203081be573be46da7c"
metafile = true

[[files]]
file = "mods/forge-config-api-port-fabric.pw.toml"
hash = "8fe2cb6a509cd81553bd5b20f19585decf8ca2beb3ae6098ce8b65517873e6b7"
metafile = true

[[files]]
file = "mods/framework-fabric.pw.toml"
hash = "afc98470b699a933cbdcc7d95822455596d91864ef14ec21a48f4fdd51d5eb03"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "d3237427c060742b9b724e0a65d57074c430f06d4f3dadf857ea5252602c8fe4"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "c9edc730013becd63a40a3faef1ce77151e5e9f92053f1b8343a21f31db9cea4"
metafile = true

[[files]]
file = "mods/goblintraders-fabric.pw.toml"
hash = "32ee7a7170ed798a1e4d8b4bd98d3659566615f8c189f70ea58419a39dce1c42"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "b317e1c2f98661a87bee6f513952ccdae3b2959232003c1905b9ceda4fbd1f8d"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6485576ef1f09940a84fa1ecb86c68867d1ae8870041d6b622d9c1fb6989b6e2"
metafile = true

[[files]]
file = "mods/magnesium-extras.pw.toml"
hash = "3ba3f3ac64c3c309f1f345349f3b7a91fb2ae2879ab5498d6e5746af357a72dc"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "c287c48033da3b704cc6d991948307061420f74034830b237dd5958ef578a9af"
metafile = true

[[files]]
file = "mods/moogs-end-structures.pw.toml"
hash = "d820d18dbd59898ae1432e75d802c2a203d5d4630752ed63e56070b678316919"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "55c98502401dc3ed8ebd886489f7b115f840866884f97b8c1abc8388d78ef20a"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "5f3e4e66e62b6b0b1665a5ddcf4c5656e8f7d2a64e4f2406366145412add08c8"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5553f08402ff3f277f68bf132463f187d14e2b12275ae319f934e4672f4b9288"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "ead2bfc6e6fa3d1f1d82a7f4968ab2c8a712866d635d1875f02936f9ad8aef02"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "c7a632600334f8643c3dca388a7e6b6b30f15607d21dd7cb1bad3f59a52f0f84"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "07464b9ca1db5514b90b0d0542c259ba9ff3403f4dfa180865c1a476bec95b42"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "8c72cc6704cd3062268260d0760bfb6152f463ca00783f8f8872c7706e3eec30"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "a716c1404c8efc8fc3c5dc9301253cb2b606ded2062d601b8e237e2266b7cd81"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "a3fd3c635d098e4479f6a5f35efbe8e3eaab7848c649af38049f5d52b6a49530"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "eecc1e73468a6899c4e8365ea1e2d681f65c603c9bb64c061f4793f4aa6351fe"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "e55b03c3a668bf4a5f6bb326921daebed4e83afd6a86796a53865c25f043ab67"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "14d93fc45d0cf8a4bd5e2446314c52d14f2f3850b10c36f7195554e3457ce979"
metafile = true

[[files]]
file = "mods/terrablender-fabric.pw.toml"
hash = "b69ac7037683a4ff97a93efb144075708409de8207d6572d56dbcc69c2025445"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "00a0cba74675174812eea16aca533adfe9bac7b30a81a7e33dd81bd9343b45c4"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "d9bfec2cf36b6bae2d85a1136560e047ab8ce1b0e9798e7b6be5d0670f65fb55"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-fabric.pw.toml"
hash = "d4c85656786ae507297bee0346612c7a23af76533c2455723543e104b4089bf7"
metafile = true

[[files]]
file = "mods/yungs-api-fabric.pw.toml"
hash = "238ac28ffc1a311a782fa569021f3cfc93c2d5ed7773b3273fdef736b80d9fb3"
metafile = true

[[files]]
file = "mods/yungs-better-caves-fabric.pw.toml"
hash = "9592e8c5b7b2437995dee44152ffbe4453253e340d86841d72d3c2b30e9ddcdb"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples-fabric.pw.toml"
hash = "129c4bbfa9c25574433eee4205ad3136d91027af612ff850a941d634d4051f62"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons-fabric.pw.toml"
hash = "e20fd212ab36de5e8e10adc05087ccb28861d05afeab8f7ab5a22b4c1197ceea"
metafile = true

[[files]]
file = "mods/yungs-better-end-island-fabric.pw.toml"
hash = "a24a457628010726f99089cf342eceebab5d0d76168af2705686b79f92b80964"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples-fabric.pw.toml"
hash = "cd50e5cd765566a7da26153f8000913de415dd536e213f535009f8d4dd5cc3c7"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.pw.toml"
hash = "4b051a6f31f33f629199e2033a5773fa25e24fcdaebf250c96f95a96f629b758"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses-fabric.pw.toml"
hash = "c813b4aaebbdec8b97874334333fcb2fe606ad6473fe44f2cc48c6f74df12393"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments-fabric.pw.toml"
hash = "42b17d95baef2a67c36a91d3cbdef1a7a0858852792a8fd9b67b1c5ca6960658"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.pw.toml"
hash = "520012b82bfa92bbd6ac71855d16119eaa7e4c3e7e29234ac00f4861dbd4b44b"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts-fabric.pw.toml"
hash = "48cd5e6fc8bc8951f0e33e21d49d4c59dcbae57134e6c7425371ae566aaf6de7"
metafile = true

[[files]]
file = "mods/yungs-bridges-fabric.pw.toml"
hash = "4147ca397d51f92d2aa93d07d4fc24bd09774724088072baf73f5f39aec074f1"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes-fabric.pw.toml"
hash = "f51562b7a2f43faf1bf9eea1262e595a18513bf1e26117c044057d811f02a2b7"
metafile = true

[[files]]
file = "mods/yungs-extras-fabric.pw.toml"
hash = "c61d03ecba29f1d678c110b37010eabeb207006c7d00966b379b92edbd69f773"
metafile = true
