hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "580b2a6104e9752febcba6c6906b4159ed87af0e06459c635ca75c9e6ca9adc2"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "59c9a1f969edd0ba1da9ba5ad6975951513225d0304a692c3d4c862e2360940c"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "90a4a53ba57a0a73c50f854d26e10bcb05cbc524a3e5c563d9a424638a5a55f6"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "ef33cbb395c6134bbe46914da62f9690d89cb5c35b827ca23dd0870a61683d5f"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "0770a75ddeedea656aa201cb4463d50d0ca2c03d445d110092c2080768a2b229"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "634bc593b540a12cf72a81dbcd924717eade71f93cda23b55b1b389257bec987"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "9716d15e12bf3d030d9655176cc66f8a336560e3f445bc0f4825d70dc4ef6247"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "280a5fc2561fec994f8464db37d17b21f03071fd94fbb728f725a33dff1a4261"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "4baa085389f32db3bb9342011832499f3f92fecfe27194232a7ad16404675faf"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0a2fce5c655c27ac938dce856e22395edb34de3b8a0f9ae0c3757d864a435ff7"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2d9b4e39fffd86cd3f3f8eaa5f132ecdd59b36d4364691ec0a7851b026cc59b7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c78021d923ba3e0dd2a4060b4fa4addd343974313cf3278f9e36359e903f442c"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "910f09506aef1e066631306ab1e9860350e1c1a22d0820abc506df3ec7c54651"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c2a2f47ca44ea2a835e4864e03ea25fd3f78b6c85f3c2608bbf6cf0fe3bcf8e5"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "3a37f452485e16f15a044572da46c48891015ae86c78d8268cb77078e6ca4f4f"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "7fc7c736a349c805ea853ddd96c6e8f2eeaeba7d069f69da9de2b17ae0984a16"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "218660e51945b076e40db1bf7a458d72f0d8d1c8f8c4a400d9bbbee7023f428d"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "6070a1aeef940a62d827accd07db0650492fbf172ab01b8898143378f32fba96"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "650d83f19ef2c073e57dfc087226fe029c0aa6d12cfdd57a091666a216bb5d15"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
hash = "2739be231b1b5c29f97594c3ba3cb8b822684295934e7d2455eb6d15331b7a32"
metafile = true

[[files]]
file = "mods/deep-aether.pw.toml"
hash = "7aa415b7ead3466d0845d147b52a58df023c5c9753be197408dcaacfb525d079"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "84acb627f6b33af289d26d1622a61b28de99306eb863d679c865f6313de49e5d"
metafile = true

[[files]]
file = "mods/ecologics.pw.toml"
hash = "32f51532a5c9b47280c70fc8efb4168f1c2162c092318a21555b74df31cc9494"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "dbcd29925710960b4ec924b7ff477b1947115b36015296ddd544f69ebfe84d18"
metafile = true

[[files]]
file = "mods/enders-delight.pw.toml"
hash = "d3bb9bfe1743e55f4059e204deb71857f636091ffea44b93a44bd4bdfec46705"
metafile = true

[[files]]
file = "mods/endremastered.pw.toml"
hash = "6b06c4782071850885806ce20372696d7cb5cf710c869221f4d7658dd8b7568d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5a23e6eae5dedec0480a03c390846c64e6c22c341bc90d898fb661f40c9b8135"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "b46a29622468f51ad3df5b83bb9b12c90a7ec33ec81126216b560ba8f9aae4b4"
metafile = true

[[files]]
file = "mods/falling-leaves-forge.pw.toml"
hash = "4da21d1d93679d000749ac4ca2abbd3baf81202db88cbfd275a6c24d954c19c8"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f5b40ddd05930fbfe8463ef8deda90177d718b61a77df977ec7a5afb88bab04"
metafile = true

[[files]]
file = "mods/farmers-structures.pw.toml"
hash = "b01e93825d94f831296825aa6ffc77e5f6636c288b477c5a939deb3ad52f9b93"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ea72f1530367a4f8c347e197119188d25d876f3fe4ac19c1eb0b4c2ad23ce48c"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "a993be38c900a36256999087cc0c2af85421216e8c66ae6a82563a3d0bcaf10b"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d9bda0972d67ea367f8e5f20ef0cf0455862f36de5ce9099b6ae0f061e4c9b62"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "5c3029e98c7c1602ba702d8042314caa6fddd952bef946f0a8d51e423a06e057"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "98faa2d8cd3b2404312dcf013038e748a3b1c1a062a406113fc9e88460ee033a"
metafile = true

[[files]]
file = "mods/goblin-traders.pw.toml"
hash = "2032f4950c195982fd90e155c18bc7151818c2508da7c658c0556a36fe7b4262"
metafile = true

[[files]]
file = "mods/hypertubes.pw.toml"
hash = "9cf4f96723390d33bf74c5e5c4679ca0f9c304865333bd3e048bac671be7d2e8"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "be345dd7f27822ede8ff64a972e36e12befef5b0c0283dd45b683475cf6ca6df"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
hash = "396e31ab3c5213019bd613e186e08fd4f2dbc56e28c13a0fc9d6c63e91b65ee8"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7ba4d1d18d87636fe6a59791c3c23c91eb03037a74e14b130e2157f8189b9f0e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "540706ab9db0907199fcc08ac62c8f0b291f7ce5b01a90e426f0b6c76c76b51c"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "91605c2be19f14456bf0f5d71ca1a3d38c2ddedd4fd3bd7fd9bb89c4d6c3cdd5"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
hash = "ae1c80edb194970a5994607b6f402c768a371d67d2f800bb0a9b213f9276334d"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "c413370b4d4364305f66095e5f363acb4a01b2d1409b6e8d5e302e31c68cff74"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b98744192d8b63a91361eb7bdec29a03c2cb95fc700b879826c27b9dc7af28ec"
metafile = true

[[files]]
file = "mods/moogs-end-structures.pw.toml"
hash = "c55f879cd44787e1cff9b894e3b10f64f39f826f3c6651c529fd437ab83af498"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "6b661b3c25388747a887e1bfdd749d27122d581a1cef48823c07666501e09644"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "8a1531616a5ae369bd32f5371b17452ef3f02b99fe0b04c1621bcac781aa5c2c"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "9c397c30fb4fd8e1976033e50182f2075afe608e8c5506b77db0ba2f6bdb060f"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "c45af825eb134dd15b18c9f0b94c05e54cea8353734222f2dbaa5531a62d55a1"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7811b7b4781993dbb63e303a4ff21bacd555b3b56d1ad979e7561d1df0101ebb"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3db5943419e6b6f4e33946266be8797230434573bc68dbe3a77d72f19001ae0c"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "5cd30923f8e867bc3a93b84d2c5853c9b6247d8287d276b993ad56629ebb07e1"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "98341e9765f45c38727a53e93600dbc25c678cf740a4a398e723fb07d5f49fcc"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a4a26382991e10fa067c2bd8bbeb754ced41c2cfaedb54967c192986a2837e23"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "00decabe50870a59262d3a50ac05e7f608439490a3285a6c979266039c2fe911"
metafile = true

[[files]]
file = "mods/repurposed-structures.pw.toml"
hash = "0706e47731396869f53bbc783c7fdd05ab61d9326b18809661e14f35e27c399e"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "fe873c740d4e392cd164f67a694b7e75169eb97003df172e4fa447659bfd07e6"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8106655a48c2a0e67771c32f092a2904eb6e0f31df26c031f38a9b9004dd9fb9"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "c150b2a60128cad4bd32ea0d3106502241ad234f1ad355ad3b98d0ac82324589"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "b3950dabe336b41172469dc99558a9a54cdba00f65797c73499232e7f75e4242"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "1c838d1869fcf4d590888e54e9f4647563bc1310f4fe519bd0beb875710f087d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "3f5fbd50ca3ca8175805dd3dac7d207aba4f280765fbfbda39caf4cd265c2a95"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "2d956e6cb0c5a465f6d3e3b81e841b5113c5ad95f8a73837375c3a66186b2c0a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c04ad2e883943640d5bc8e519c0b90e6cdd11e5b5a6d095b5838c477021771a0"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "188c4f2d172fb97af9a58db32c3e37900b0bae5aa742a0fb0637aebaed8a6aea"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "f114030e6984e30307fc43e37ec812c915aed7f64717d7b364dd84008e045fe4"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "05065c99b76965afd2fbe232651517664898216646e657f1a2c6121e55730179"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "9f159ae4b4afbcb7e9ac53035fc4c11ec3d622e31e089ff44cfc836ab763cce6"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "fd8994221802e444c1b1b2da9d3d816a040860d875c56ce15be401b865e2eae5"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "d567dd23fb4b89cb0b9577f7b8dc82c778a85e97cca140ced00f177abb72e63d"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "43c8d26df567c314b7432ec4bd0c00ce51b96af904251813f58bc9ba8f7354f1"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "8765410f815e684571d71ba23afa3609a78eb1ae811ad4bbde2eedf0c2773fc1"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "b51ffb9c659f76d16b56f5c1a21892b92cc5bf0ea27a539aab39f8125d1d849f"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "c928f3d43b7de0e2e3ad32a979bf3a80b4d0dc807ace21a428e4ab1dd3728f3f"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "b72e6f1205d71d4be69def5773f99f53c1ea4ec6a37206465ee9f1fe0fbb9a96"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "872a589a61991b8d1c9f8ec62e95392e866c375ca27fcfab093c3ac3e14f5a12"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "dd70400c5d2ab2f563f373884dac29fc1b96580e76fbc5dd97154c32dccf27d3"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "bd6ae6d272ae1851f04636f9b53a3133726dbab79df7a4c4c4b55a42f6450058"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "21cf2503b84b88d8e3bd55c12cf365add4f0bb385871664d95cf9ae26b34ab93"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "0de22f9bdf1c0337fb78d107b5e28ef7c0fd0de2feb7ba6c9b54a65a30343863"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "e3e0a1c688c27292d5f5f536cac1c8143c4ed90a93def213d6c51b87984ccdc8"
metafile = true
