name = "iop-fabric"
author = "willisuper2000"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42d6346fede297c4135df7d53365563871de81c3a212f55d856564136447014b"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
