name = "iop-fabric"
author = "willisuper2000"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfe75ea2ea8f6cb50b4f20172213411bb7340f6a172953bb4e40c9c88ab7fb1"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
