name = "IOP Jai Hind"
author = "Willi1000"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4f512da97468f802e7d5f9c7b32dd031284dfc41847dcd66e2d8f585c403d9a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
