name = "IOP Jai Hind"
author = "Willi1000"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac5421a72d4d71c12342562dcdcf3c7be4042e60fd0bdab4bcefb87b7e057ca3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
