name = "IOP Jai Hind"
author = "Willi1000"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a2526c37199197e535c4356bf82dbe9049f412ce72cfdc9d691fed6e4178e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
